---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: observability
  name: observability-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vagrant/workspace/observability-pv